name: Test

on:
  pull_request: {}
  push:
    branches: master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
            cache: "poetry"
            python-version: "3.10"

      - run: |
            pip install pipx
            pipx install poetry

      - name: Install dependencies with poetry
        run: /root/.local/bin/poetry install

      - run: /root/.local/bin/poetry run isort --diff .
      - run: /root/.local/bin/poetry run black --check .
      - run: /root/.local/bin/poetry run flake8
      - run: /root/.local/bin/poetry run mypy
      - run: /root/.local/bin/poetry run pytest --cov --cov-report=xml

      - name: Upload Coverage to Codecov
        uses: codecov/codecov-action@v3
