name: Test

on:
  pull_request: {}
  push:
    branches: master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - run: |
          pip install pipx
          pipx install poetry

      - name: Install dependencies with poetry
        run: poetry install

      - run: poetry run isort --diff .
      - run: poetry run black --check .
      - run: poetry run flake8
      - run: poetry run mypy
      - run: poetry run pytest --cov --cov-report=xml

      - name: Upload Coverage to Codecov
        uses: codecov/codecov-action@v3
